### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by xxFLORII** [PocketCloudSystem/PocketCloud#1]
**Your idea**
Rename „Plugin“ to „CloudPlugin“

**Comment by r3pt1s** [comment]
Where should i do that?

**Comment by xxFLORII** [comment]
Wo? im CloudSystem \src\pocketcloud\plugin\

**Comment by r3pt1s** [comment]
Ne ich lass das erstmal so wäre zwar bestimmt auch schöner weil die Server Klasse heißt auch CloudServer genauso wie Player aber erstmal lass ich das so
